site_name: Get-up Recording

site_url: https://helinxu.github.io/getup/

extra:
  homepage: https://helinxu.github.io/getup/

extra_css:
  # - stylesheets/extra.css
  - stylesheets/gothic.css

theme:
  name: material
  features:
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    - header.autohide
    - navigation.footer
  language: en
  logo: assets/landscape/M1.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: assets/landscape/M2.svg

  palette:
    primary: white
    accent: light green

nav: 
  - Recording: index.md
